# Generated by Django 2.2.1 on 2019-05-10 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitud',
            new_name='Solicitudes',
        ),
    ]
